version: '2'
services:
    web:
        environment:
            - PORT=5000
        build: .
        ports:
            - "5000:5000"
        volumes:
            - .:/code
        depends_on:
            - redis
    redis:
        image: redis
        ports:
            - "6379:6379"
